# Generated by Django 5.2.1 on 2025-05-13 10:32

import app_model.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('div_geo_code', models.CharField(max_length=2)),
                ('div_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('div_name_bng', models.CharField(max_length=200)),
                ('sorting_order', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lkp_division',
                'ordering': ['div_name'],
            },
        ),
        migrations.CreateModel(
            name='MapLegend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.CharField(max_length=50)),
                ('category_name', models.CharField(blank=True, max_length=200, null=True)),
                ('display_header', models.CharField(blank=True, max_length=200, null=True)),
                ('legend_color', models.CharField(blank=True, max_length=200, null=True)),
                ('legend_value', models.CharField(blank=True, max_length=256, null=True)),
                ('sorting', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('watershed_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_map_legend',
            },
        ),
        migrations.CreateModel(
            name='MapShapeFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.CharField(blank=True, max_length=100, null=True)),
                ('category_name', models.CharField(blank=True, max_length=250, null=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to=app_model.models.map_files_path)),
                ('is_active', models.BooleanField(default=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'tbl_map_files',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('dist_geo_code', models.CharField(max_length=4)),
                ('dist_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('dist_name_bng', models.CharField(max_length=200)),
                ('sorting_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_model.division')),
            ],
            options={
                'db_table': 'lkp_district',
                'ordering': ['dist_name'],
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_category', models.CharField(blank=True, default='pending', max_length=50, null=True)),
                ('user_role', models.CharField(blank=True, default='pending', max_length=100, null=True)),
                ('user_status', models.CharField(blank=True, default='pending', max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_user_details',
            },
        ),
        migrations.CreateModel(
            name='Watershed',
            fields=[
                ('watershed_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('watershed_name', models.CharField(max_length=200)),
                ('watershed_name_bng', models.CharField(blank=True, max_length=200)),
                ('serial', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('district', models.ForeignKey(db_column='district_name', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_model.district')),
            ],
            options={
                'db_table': 'lkp_watershed',
                'ordering': ['watershed_code'],
            },
        ),
    ]
