# Generated by Django 4.2.10 on 2025-09-11 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapGallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('map_type', models.CharField(blank=True, max_length=200, null=True)),
                ('map_file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('map_display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('watershed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_model.watershed')),
            ],
            options={
                'db_table': 'tbl_map_gallery',
                'ordering': ['-created_at'],
            },
        ),
    ]
