# Generated by Django 4.2.10 on 2025-06-03 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climateresilience',
            name='parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='climate_resiliences', to='app_model.parameters'),
        ),
        migrations.AlterField(
            model_name='climateresilience',
            name='watershed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='climate_resiliences', to='app_model.watershed'),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='app_model.components'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='app_model.indicators'),
        ),
        migrations.AlterField(
            model_name='watershedhealth',
            name='parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watershed_healths', to='app_model.parameters'),
        ),
        migrations.AlterField(
            model_name='watershedhealth',
            name='watershed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watershed_healths', to='app_model.watershed'),
        ),
    ]
