# Generated by Django 4.2.10 on 2025-06-23 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatershedOverallStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('watershed_status_id', models.IntegerField(blank=True, null=True)),
                ('watershed_name', models.CharField(blank=True, max_length=200, null=True)),
                ('number_of_para', models.IntegerField(blank=True, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('total_population', models.IntegerField(blank=True, null=True)),
                ('male', models.IntegerField(blank=True, null=True)),
                ('female', models.IntegerField(blank=True, null=True)),
                ('number_of_household', models.IntegerField(blank=True, null=True)),
                ('number_of_community', models.CharField(blank=True, max_length=250, null=True)),
                ('baseline', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_2030', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_2035', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_2041', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_2050', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('watershed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_model.watershed')),
            ],
            options={
                'db_table': 'tbl_watershed_overall_status',
                'ordering': ['-created_at'],
            },
        ),
    ]
