# Generated by Django 5.2.1 on 2025-05-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParaMapLegend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('watershed_id', models.CharField(max_length=100)),
                ('legend_title', models.CharField(blank=True, max_length=100, null=True)),
                ('para_name', models.CharField(blank=True, max_length=100, null=True)),
                ('legend_color', models.CharField(blank=True, max_length=50, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('sorting', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_para_map_legend',
            },
        ),
    ]
