# Generated by Django 4.2.10 on 2025-06-23 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0002_watershedoverallstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watershedoverallstatus',
            name='watershed_status_id',
        ),
    ]
