# Generated by Django 4.2.10 on 2025-06-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0002_alter_climateresilience_parameter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watershedhealth',
            name='watershed',
        ),
        migrations.AddField(
            model_name='watershedhealth',
            name='watershed_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order'),
        ),
    ]
