# Generated by Django 4.2.10 on 2025-09-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0002_mapgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kp_type', models.CharField(blank=True, max_length=200, null=True)),
                ('report_title', models.CharField(blank=True, max_length=200, null=True)),
                ('study_watershed_or_region', models.CharField(blank=True, max_length=200, null=True)),
                ('doc_type', models.CharField(blank=True, max_length=100, null=True)),
                ('report_link', models.CharField(blank=True, max_length=300, null=True)),
                ('report_thumbnail_file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'tbl_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
