# Generated by Django 4.2.10 on 2025-06-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0002_climateresilience_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatershedHealth',
        ),
    ]
