# Generated by Django 4.2.10 on 2025-06-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0003_delete_watershedhealth'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatershedHealth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baseline_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_2030', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_2035', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_2041', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_2050', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_special', models.BooleanField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watershed_healths', to='app_model.parameters')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watershed_healths', to='app_model.units')),
                ('watershed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watershed_healths', to='app_model.watershed')),
            ],
            options={
                'db_table': 'tbl_watershed_health',
                'ordering': ['-created_at'],
            },
        ),
    ]
