# Generated by Django 4.2.10 on 2025-06-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0003_remove_watershedhealth_watershed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watershedhealth',
            name='watershed_id',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
