# Generated by Django 4.2.10 on 2025-09-18 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0003_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conservation_Measure_Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('con_measure_category_name', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'lkp_con_measure_categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conservation_Measure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('conservation_measure_name', models.CharField(blank=True, max_length=200, null=True)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('conservation_measure_categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_model.conservation_measure_categories')),
            ],
            options={
                'db_table': 'tbl_conservation_measure',
                'ordering': ['-created_at'],
            },
        ),
    ]
