# Generated by Django 4.2.10 on 2025-06-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0004_watershedhealth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClimateResilience',
        ),
    ]
