# Generated by Django 4.2.10 on 2025-06-23 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0004_alter_watershedhealth_watershed_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='watershedhealth',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watershed_healths', to='app_model.units'),
        ),
    ]
